import SwiftUI
import Defaults
import LaunchAtLogin
import GoogleSignIn

// MARK: - Design Tokens

private enum Design {
    static let cornerRadius: CGFloat = 8
    static let spacing: CGFloat = 12
    static let padding: CGFloat = 16
}

// MARK: - Settings View

struct SettingsView: View {
    @Environment(\.dismiss) private var dismiss
    @StateObject private var settings = SettingsManager.shared
    @State private var configuringPlatform: Platform?

    var body: some View {
        VStack(spacing: 0) {
            // Header with close button
            HStack {
                Text("Settings")
                    .font(.headline)
                Spacer()
                Button(action: { dismiss() }) {
                    Image(systemName: "xmark.circle.fill")
                        .font(.title2)
                        .foregroundColor(.secondary)
                }
                .buttonStyle(.plain)
                .keyboardShortcut(.cancelAction)
            }
            .padding(.horizontal, Design.padding)
            .padding(.top, Design.padding)
            .padding(.bottom, 8)

            TabView {
                GeneralSettingsTab()
                    .tabItem { Label("General", systemImage: "gearshape") }

                PlatformsSettingsTab(configuringPlatform: $configuringPlatform)
                    .tabItem { Label("Platforms", systemImage: "app.connected.to.app.below.fill") }

                AISettingsTab()
                    .tabItem { Label("AI", systemImage: "sparkles") }
            }
        }
        .frame(width: 520, height: 450)
        .sheet(item: $configuringPlatform) { platform in
            PlatformConfigSheet(platform: platform) {
                configuringPlatform = nil
            }
        }
    }
}

// MARK: - General Settings Tab

private struct GeneralSettingsTab: View {
    @State private var diagnosticInfo: String = ""
    @State private var showingDiagnostics = false

    var body: some View {
        Form {
            Section {
                LaunchAtLogin.Toggle("Launch at login")

                DatePicker(
                    "Morning fetch time",
                    selection: Binding(
                        get: { Defaults[.morningTime] },
                        set: { Defaults[.morningTime] = $0 }
                    ),
                    displayedComponents: .hourAndMinute
                )
            }

            Section("Notifications") {
                Toggle("Show badge count", isOn: Binding(
                    get: { Defaults[.morningNotifications] },
                    set: { Defaults[.morningNotifications] = $0 }
                ))
            }

            Section("Behavior") {
                Toggle("Auto-generate response drafts", isOn: Binding(
                    get: { Defaults[.autoGenerateDrafts] },
                    set: { Defaults[.autoGenerateDrafts] = $0 }
                ))
            }

            Section("Debug") {
                Button("Run Diagnostics") {
                    Task {
                        diagnosticInfo = await InboxManager.shared.getDiagnostics()
                        showingDiagnostics = true
                    }
                }
                .buttonStyle(.bordered)

                Text("Check Console.app for detailed logs")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
        }
        .formStyle(.grouped)
        .padding(Design.padding)
        .sheet(isPresented: $showingDiagnostics) {
            DiagnosticsSheet(info: diagnosticInfo)
        }
    }
}

// MARK: - Diagnostics Sheet

private struct DiagnosticsSheet: View {
    let info: String
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Text("Diagnostics")
                    .font(.headline)
                Spacer()
                Button(action: { dismiss() }) {
                    Image(systemName: "xmark.circle.fill")
                        .font(.title2)
                        .foregroundColor(.secondary)
                }
                .buttonStyle(.plain)
            }
            .padding()

            Divider()

            ScrollView {
                Text(info)
                    .font(.system(.body, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
            }

            Divider()

            HStack {
                Button("Copy") {
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(info, forType: .string)
                }
                .buttonStyle(.bordered)

                Spacer()

                Button("Close") {
                    dismiss()
                }
                .keyboardShortcut(.cancelAction)
            }
            .padding()
        }
        .frame(width: 500, height: 400)
    }
}

// MARK: - Platforms Settings Tab

private struct PlatformsSettingsTab: View {
    @StateObject private var settings = SettingsManager.shared
    @Binding var configuringPlatform: Platform?

    var body: some View {
        ScrollView {
            VStack(spacing: Design.spacing) {
                ForEach(Platform.allCases) { platform in
                    PlatformRow(
                        platform: platform,
                        onConfigure: { configuringPlatform = platform }
                    )
                }
            }
            .padding(Design.padding)
        }
    }
}

// MARK: - Platform Row

private struct PlatformRow: View {
    let platform: Platform
    let onConfigure: () -> Void

    @StateObject private var settings = SettingsManager.shared

    private var connectionMethod: ConnectionMethod {
        settings.getConnectionMethod(for: platform)
    }

    private var isConfigured: Bool {
        settings.isPlatformConfigured(platform)
    }

    var body: some View {
        HStack(spacing: Design.spacing) {
            // Platform icon
            Image(systemName: platform.iconName)
                .font(.title2)
                .foregroundColor(platform.accentColor)
                .frame(width: 32, height: 32)

            // Platform info
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(platform.displayName)
                        .font(.headline)

                    if isConfigured {
                        Text("•")
                            .foregroundColor(.secondary)
                        Text(connectionMethod.displayName)
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                }

                Text(statusText)
                    .font(.caption)
                    .foregroundColor(statusColor)
            }

            Spacer()

            // Actions
            if isConfigured {
                Toggle("", isOn: Binding(
                    get: { settings.isPlatformEnabled(platform) },
                    set: { settings.setPlatformEnabled(platform, enabled: $0) }
                ))
                .labelsHidden()
                .toggleStyle(.switch)

                Button("Edit") {
                    onConfigure()
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
            } else {
                Button("Set Up") {
                    onConfigure()
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.small)
            }
        }
        .padding(Design.spacing)
        .background(Color(nsColor: .controlBackgroundColor))
        .cornerRadius(Design.cornerRadius)
    }

    private var statusText: String {
        if isConfigured {
            return settings.isPlatformEnabled(platform) ? "Connected" : "Disabled"
        }
        return "Not configured"
    }

    private var statusColor: Color {
        if isConfigured {
            return settings.isPlatformEnabled(platform) ? .green : .secondary
        }
        return .secondary
    }
}

// MARK: - AI Settings Tab

private struct AISettingsTab: View {
    @StateObject private var settings = SettingsManager.shared
    @State private var isEditingAPIKey = false
    @State private var apiKeyInput = ""

    private var hasAPIKey: Bool {
        settings.getCredential(platform: .gmail, key: "claude_api_key") != nil
    }

    var body: some View {
        Form {
            Section("Claude API") {
                HStack {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("API Key")
                        if hasAPIKey {
                            Text("Configured")
                                .font(.caption)
                                .foregroundColor(.green)
                        }
                    }

                    Spacer()

                    if isEditingAPIKey {
                        SecureField("sk-ant-...", text: $apiKeyInput)
                            .textFieldStyle(.roundedBorder)
                            .frame(width: 180)

                        Button("Save") {
                            if !apiKeyInput.isEmpty {
                                settings.setCredential(platform: .gmail, key: "claude_api_key", value: apiKeyInput)
                            }
                            apiKeyInput = ""
                            isEditingAPIKey = false
                        }
                        .buttonStyle(.borderedProminent)
                        .controlSize(.small)

                        Button("Cancel") {
                            apiKeyInput = ""
                            isEditingAPIKey = false
                        }
                        .controlSize(.small)
                    } else {
                        Button(hasAPIKey ? "Change" : "Add Key") {
                            isEditingAPIKey = true
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                    }
                }

                Text("Get your API key from console.anthropic.com")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Section("Response Style") {
                Picker("Default tone", selection: Binding(
                    get: { Draft.Tone(rawValue: Defaults[.draftTone]) ?? .professional },
                    set: { Defaults[.draftTone] = $0.rawValue }
                )) {
                    ForEach(Draft.Tone.allCases, id: \.self) { tone in
                        Text(tone.displayName).tag(tone)
                    }
                }
            }

            Section("Model") {
                HStack {
                    Text("Model")
                    Spacer()
                    Text("Claude Sonnet 4")
                        .foregroundColor(.secondary)
                }
            }

            Section {
                HStack(spacing: 4) {
                    Image(systemName: "lock.shield.fill")
                        .font(.caption)
                    Text("API key stored locally in your Mac's Keychain")
                        .font(.caption)
                }
                .foregroundColor(.secondary)
            }
        }
        .formStyle(.grouped)
        .padding(Design.padding)
    }
}

// MARK: - Platform Config Sheet

struct PlatformConfigSheet: View {
    let platform: Platform
    let onDismiss: () -> Void

    @StateObject private var settings = SettingsManager.shared
    @State private var selectedMethod: ConnectionMethod
    @State private var credentials: [String: String] = [:]
    @State private var showingRemoveAlert = false

    init(platform: Platform, onDismiss: @escaping () -> Void) {
        self.platform = platform
        self.onDismiss = onDismiss
        _selectedMethod = State(initialValue: SettingsManager.shared.getConnectionMethod(for: platform))
    }

    var body: some View {
        VStack(spacing: 0) {
            // Header
            header

            Divider()

            // Content
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    connectionMethodPicker

                    if selectedMethod.requiresCredentials {
                        credentialsForm
                    } else {
                        desktopIntegrationInfo
                    }
                }
                .padding(20)
            }

            Divider()

            // Footer
            footer
        }
        .frame(width: 440, height: 400)
        .onAppear(perform: loadCredentials)
        .onChange(of: selectedMethod) { _ in
            loadCredentials()
        }
        .alert("Remove Connection?", isPresented: $showingRemoveAlert) {
            Button("Cancel", role: .cancel) { }
            Button("Remove", role: .destructive) {
                removeConnection()
            }
        } message: {
            Text("This will remove all saved credentials for \(platform.displayName).")
        }
    }

    private var header: some View {
        HStack {
            Image(systemName: platform.iconName)
                .font(.title2)
                .foregroundColor(platform.accentColor)

            Text(platform.displayName)
                .font(.headline)

            Spacer()

            Button(action: onDismiss) {
                Image(systemName: "xmark.circle.fill")
                    .font(.title2)
                    .foregroundColor(.secondary)
            }
            .buttonStyle(.plain)
        }
        .padding(16)
    }

    private var connectionMethodPicker: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Connection Method")
                .font(.subheadline)
                .foregroundColor(.secondary)

            VStack(spacing: 8) {
                ForEach(platform.connectionMethods) { method in
                    ConnectionMethodOption(
                        method: method,
                        isSelected: selectedMethod == method,
                        onSelect: { selectedMethod = method }
                    )
                }
            }
        }
    }

    private var credentialsForm: some View {
        VStack(alignment: .leading, spacing: 12) {
            // Show Google Sign-In button for Gmail OAuth
            if selectedMethod == .gmailOAuth {
                googleSignInSection
            } else {
                // Regular credentials form
                Text("Credentials")
                    .font(.subheadline)
                    .foregroundColor(.secondary)

                ForEach(selectedMethod.credentialFields) { field in
                    VStack(alignment: .leading, spacing: 4) {
                        Text(field.label)
                            .font(.caption)
                            .foregroundColor(.secondary)

                        if field.isSecret {
                            SecureField(field.placeholder, text: binding(for: field.key))
                                .textFieldStyle(.roundedBorder)
                        } else {
                            TextField(field.placeholder, text: binding(for: field.key))
                                .textFieldStyle(.roundedBorder)
                        }
                    }
                }

                if let instructions = selectedMethod.setupInstructions {
                    Text(instructions)
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                if let url = selectedMethod.setupURL {
                    Link(destination: url) {
                        HStack(spacing: 4) {
                            Text("Get credentials")
                            Image(systemName: "arrow.up.right")
                        }
                        .font(.caption)
                    }
                }
            }
        }
    }

    @ViewBuilder
    private var googleSignInSection: some View {
        let googleAuth = GoogleAuthManager.shared

        VStack(alignment: .leading, spacing: 16) {
            if googleAuth.isSignedIn {
                // Already signed in
                HStack(spacing: 12) {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.title)
                        .foregroundColor(.green)

                    VStack(alignment: .leading, spacing: 4) {
                        Text("Signed in with Google")
                            .font(.headline)

                        if let email = googleAuth.userEmail {
                            Text(email)
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }

                    Spacer()

                    Button("Sign Out") {
                        googleAuth.signOut()
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                }
                .padding()
                .background(Color.green.opacity(0.1))
                .cornerRadius(Design.cornerRadius)
            } else {
                // Sign in button
                VStack(spacing: 12) {
                    Text("Sign in to access your Gmail")
                        .font(.subheadline)
                        .foregroundColor(.secondary)

                    Button {
                        Task {
                            do {
                                try await googleAuth.signIn()
                                // Auto-save after successful sign-in
                                save()
                            } catch {
                                credentials["error"] = error.localizedDescription
                            }
                        }
                    } label: {
                        HStack(spacing: 8) {
                            Image(systemName: "g.circle.fill")
                                .font(.title2)
                            Text("Sign in with Google")
                                .font(.headline)
                        }
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 12)
                    }
                    .buttonStyle(.borderedProminent)
                    .tint(Color(red: 0.26, green: 0.52, blue: 0.96))

                    if let errorMsg = credentials["error"] {
                        Text(errorMsg)
                            .font(.caption)
                            .foregroundColor(.red)
                    }

                    Divider()
                        .padding(.vertical, 8)

                    // Manual setup option
                    DisclosureGroup("Or set up manually with Client ID") {
                        VStack(alignment: .leading, spacing: 8) {
                            ForEach(selectedMethod.credentialFields) { field in
                                VStack(alignment: .leading, spacing: 4) {
                                    Text(field.label)
                                        .font(.caption)
                                        .foregroundColor(.secondary)

                                    if field.isSecret {
                                        SecureField(field.placeholder, text: binding(for: field.key))
                                            .textFieldStyle(.roundedBorder)
                                    } else {
                                        TextField(field.placeholder, text: binding(for: field.key))
                                            .textFieldStyle(.roundedBorder)
                                    }
                                }
                            }

                            if let url = selectedMethod.setupURL {
                                Link(destination: url) {
                                    HStack(spacing: 4) {
                                        Text("Create credentials in Google Cloud Console")
                                        Image(systemName: "arrow.up.right")
                                    }
                                    .font(.caption)
                                }
                            }
                        }
                        .padding(.top, 8)
                    }
                    .font(.caption)
                    .foregroundColor(.secondary)
                }
            }
        }
    }

    private var desktopIntegrationInfo: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 12) {
                Image(systemName: "checkmark.circle.fill")
                    .font(.title)
                    .foregroundColor(.green)

                VStack(alignment: .leading, spacing: 4) {
                    Text("No setup required")
                        .font(.headline)

                    if let instructions = selectedMethod.setupInstructions {
                        Text(instructions)
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                }
            }
            .padding()
            .background(Color.green.opacity(0.1))
            .cornerRadius(Design.cornerRadius)
        }
    }

    private var footer: some View {
        HStack {
            if settings.isPlatformConfigured(platform) {
                Button("Remove") {
                    showingRemoveAlert = true
                }
                .foregroundColor(.red)
            }

            Spacer()

            Button("Cancel") {
                onDismiss()
            }
            .keyboardShortcut(.cancelAction)

            Button("Save") {
                save()
            }
            .keyboardShortcut(.defaultAction)
            .buttonStyle(.borderedProminent)
        }
        .padding(16)
    }

    // MARK: - Helpers

    private func binding(for key: String) -> Binding<String> {
        Binding(
            get: { credentials[key] ?? "" },
            set: { credentials[key] = $0 }
        )
    }

    private func loadCredentials() {
        credentials = [:]
        for field in selectedMethod.credentialFields {
            if let value = settings.getCredential(platform: platform, key: field.key) {
                credentials[field.key] = value
            }
        }
    }

    private func save() {
        // Save connection method
        settings.setConnectionMethod(selectedMethod, for: platform)

        // Save credentials
        for (key, value) in credentials where !value.isEmpty {
            settings.setCredential(platform: platform, key: key, value: value)
        }

        // Enable platform
        settings.setPlatformEnabled(platform, enabled: true)

        onDismiss()
    }

    private func removeConnection() {
        settings.clearAllCredentials(for: platform)
        settings.setPlatformEnabled(platform, enabled: false)
        onDismiss()
    }
}

// MARK: - Connection Method Option

private struct ConnectionMethodOption: View {
    let method: ConnectionMethod
    let isSelected: Bool
    let onSelect: () -> Void

    var body: some View {
        Button(action: onSelect) {
            HStack(spacing: 12) {
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .foregroundColor(isSelected ? .accentColor : .secondary)

                Image(systemName: method.iconName)
                    .frame(width: 20)
                    .foregroundColor(.secondary)

                VStack(alignment: .leading, spacing: 2) {
                    Text(method.displayName)
                        .font(.body)
                        .foregroundColor(.primary)

                    Text(method.subtitle)
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                Spacer()

                Text(method.complexity.rawValue)
                    .font(.caption2)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(method.complexity.color.opacity(0.2))
                    .foregroundColor(method.complexity.color)
                    .cornerRadius(4)
            }
            .padding(10)
            .background(isSelected ? Color.accentColor.opacity(0.1) : Color(nsColor: .controlBackgroundColor))
            .cornerRadius(Design.cornerRadius)
            .overlay(
                RoundedRectangle(cornerRadius: Design.cornerRadius)
                    .stroke(isSelected ? Color.accentColor : Color.clear, lineWidth: 1)
            )
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Platform Extensions (moved from old file)

extension Platform {
    var setupHelpText: String? {
        defaultConnectionMethod.setupInstructions
    }

    var setupURL: URL? {
        defaultConnectionMethod.setupURL
    }
}

#Preview {
    SettingsView()
}
