import SwiftUI
import Defaults
import LaunchAtLogin
import GoogleSignIn

// MARK: - Design Tokens

private enum Design {
    static let cornerRadius: CGFloat = 8
    static let spacing: CGFloat = 12
    static let padding: CGFloat = 16
}

// MARK: - Settings View

struct SettingsView: View {
    @Environment(\.dismiss) private var dismiss
    @StateObject private var settings = SettingsManager.shared
    @State private var configuringPlatform: Platform?

    var body: some View {
        VStack(spacing: 0) {
            // Header with close button
            HStack {
                Text("Settings")
                    .font(.headline)
                Spacer()
                Button(action: { dismiss() }) {
                    Image(systemName: "xmark.circle.fill")
                        .font(.title2)
                        .foregroundColor(.secondary)
                }
                .buttonStyle(.plain)
                .keyboardShortcut(.cancelAction)
            }
            .padding(.horizontal, Design.padding)
            .padding(.top, Design.padding)
            .padding(.bottom, 8)

            TabView {
                GeneralSettingsTab()
                    .tabItem { Label("General", systemImage: "gearshape") }

                PlatformsSettingsTab(configuringPlatform: $configuringPlatform)
                    .tabItem { Label("Platforms", systemImage: "app.connected.to.app.below.fill") }

                AISettingsTab()
                    .tabItem { Label("AI", systemImage: "sparkles") }
            }
        }
        .frame(width: 520, height: 450)
        .sheet(item: $configuringPlatform) { platform in
            PlatformConfigSheet(platform: platform) {
                configuringPlatform = nil
            }
        }
    }
}

// MARK: - General Settings Tab

private struct GeneralSettingsTab: View {
    @State private var diagnosticInfo: String = ""
    @State private var showingDiagnostics = false

    var body: some View {
        Form {
            Section {
                LaunchAtLogin.Toggle("Launch at login")

                DatePicker(
                    "Morning fetch time",
                    selection: Binding(
                        get: { Defaults[.morningTime] },
                        set: { Defaults[.morningTime] = $0 }
                    ),
                    displayedComponents: .hourAndMinute
                )
            }

            Section("Notifications") {
                Toggle("Show badge count", isOn: Binding(
                    get: { Defaults[.morningNotifications] },
                    set: { Defaults[.morningNotifications] = $0 }
                ))
            }

            Section("Behavior") {
                Toggle("Auto-generate response drafts", isOn: Binding(
                    get: { Defaults[.autoGenerateDrafts] },
                    set: { Defaults[.autoGenerateDrafts] = $0 }
                ))
            }

            Section("Debug") {
                Button("Run Diagnostics") {
                    Task {
                        diagnosticInfo = await InboxManager.shared.getDiagnostics()
                        showingDiagnostics = true
                    }
                }
                .buttonStyle(.bordered)

                Text("Check Console.app for detailed logs")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
        }
        .formStyle(.grouped)
        .padding(Design.padding)
        .sheet(isPresented: $showingDiagnostics) {
            DiagnosticsSheet(info: diagnosticInfo)
        }
    }
}

// MARK: - Diagnostics Sheet

private struct DiagnosticsSheet: View {
    let info: String
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Text("Diagnostics")
                    .font(.headline)
                Spacer()
                Button(action: { dismiss() }) {
                    Image(systemName: "xmark.circle.fill")
                        .font(.title2)
                        .foregroundColor(.secondary)
                }
                .buttonStyle(.plain)
            }
            .padding()

            Divider()

            ScrollView {
                Text(info)
                    .font(.system(.body, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
            }

            Divider()

            HStack {
                Button("Copy") {
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(info, forType: .string)
                }
                .buttonStyle(.bordered)

                Spacer()

                Button("Close") {
                    dismiss()
                }
                .keyboardShortcut(.cancelAction)
            }
            .padding()
        }
        .frame(width: 500, height: 400)
    }
}

// MARK: - Platforms Settings Tab

private struct PlatformsSettingsTab: View {
    @StateObject private var settings = SettingsManager.shared
    @Binding var configuringPlatform: Platform?

    private var messagingPlatforms: [Platform] {
        Platform.allCases.filter { !$0.isInfoPulse }
    }

    private var pulsePlatforms: [Platform] {
        Platform.allCases.filter { $0.isInfoPulse }
    }

    var body: some View {
        ScrollView {
            VStack(spacing: Design.spacing + 8) {
                // Messaging platforms
                VStack(alignment: .leading, spacing: Design.spacing) {
                    Text("Messaging")
                        .font(.caption)
                        .fontWeight(.semibold)
                        .foregroundColor(.secondary)
                        .padding(.horizontal, 4)

                    ForEach(messagingPlatforms) { platform in
                        PlatformRow(
                            platform: platform,
                            onConfigure: { configuringPlatform = platform }
                        )
                    }
                }

                // Info pulse platforms
                VStack(alignment: .leading, spacing: Design.spacing) {
                    Text("Info Pulse")
                        .font(.caption)
                        .fontWeight(.semibold)
                        .foregroundColor(.secondary)
                        .padding(.horizontal, 4)

                    ForEach(pulsePlatforms) { platform in
                        PlatformRow(
                            platform: platform,
                            onConfigure: { configuringPlatform = platform }
                        )
                    }
                }
            }
            .padding(Design.padding)
        }
    }
}

// MARK: - Platform Row

private struct PlatformRow: View {
    let platform: Platform
    let onConfigure: () -> Void

    @StateObject private var settings = SettingsManager.shared

    private var connectionMethod: ConnectionMethod {
        settings.getConnectionMethod(for: platform)
    }

    private var isConfigured: Bool {
        settings.isPlatformConfigured(platform)
    }

    var body: some View {
        HStack(spacing: Design.spacing) {
            // Platform icon
            Image(systemName: platform.iconName)
                .font(.title2)
                .foregroundColor(platform.accentColor)
                .frame(width: 32, height: 32)

            // Platform info
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(platform.displayName)
                        .font(.headline)

                    if isConfigured {
                        Text("•")
                            .foregroundColor(.secondary)
                        Text(connectionMethod.displayName)
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                }

                Text(statusText)
                    .font(.caption)
                    .foregroundColor(statusColor)
            }

            Spacer()

            // Actions
            if isConfigured {
                Toggle("", isOn: Binding(
                    get: { settings.isPlatformEnabled(platform) },
                    set: { settings.setPlatformEnabled(platform, enabled: $0) }
                ))
                .labelsHidden()
                .toggleStyle(.switch)

                Button("Edit") {
                    onConfigure()
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
            } else {
                Button("Set Up") {
                    onConfigure()
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.small)
            }
        }
        .padding(Design.spacing)
        .background(Color(nsColor: .controlBackgroundColor))
        .cornerRadius(Design.cornerRadius)
    }

    private var statusText: String {
        if isConfigured {
            return settings.isPlatformEnabled(platform) ? "Connected" : "Disabled"
        }
        return "Not configured"
    }

    private var statusColor: Color {
        if isConfigured {
            return settings.isPlatformEnabled(platform) ? .green : .secondary
        }
        return .secondary
    }
}

// MARK: - AI Settings Tab

private struct AISettingsTab: View {
    @StateObject private var settings = SettingsManager.shared
    @StateObject private var claudeManager = ClaudeManager.shared
    @State private var isEditingAPIKey = false
    @State private var apiKeyInput = ""
    @State private var testError = ""
    @State private var showingRepairSheet = false

    private var hasAPIKey: Bool {
        settings.getCredential(platform: .gmail, key: "claude_api_key") != nil
    }

    var body: some View {
        Form {
            // Self-Healing Section
            Section("Self-Healing") {
                HStack {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("Claude Code CLI")
                        Text(claudeManager.canSelfHeal ? "Available" : "Not installed")
                            .font(.caption)
                            .foregroundColor(claudeManager.canSelfHeal ? .green : .secondary)
                    }

                    Spacer()

                    if claudeManager.canSelfHeal {
                        Image(systemName: "checkmark.circle.fill")
                            .foregroundColor(.green)
                    } else {
                        Link("Install", destination: URL(string: "https://claude.ai/download")!)
                            .font(.caption)
                    }
                }

                if claudeManager.canSelfHeal {
                    Toggle("Auto-fix build errors", isOn: Binding(
                        get: { Defaults[.autoFixErrors] },
                        set: { Defaults[.autoFixErrors] = $0 }
                    ))

                    // Test repair button
                    HStack {
                        TextField("Paste build error to test", text: $testError, axis: .vertical)
                            .textFieldStyle(.roundedBorder)
                            .lineLimit(2...4)

                        Button {
                            showingRepairSheet = true
                        } label: {
                            if claudeManager.isRepairing {
                                ProgressView()
                                    .scaleEffect(0.7)
                            } else {
                                Text("Fix")
                            }
                        }
                        .buttonStyle(.borderedProminent)
                        .disabled(testError.isEmpty || claudeManager.isRepairing)
                    }

                    if let result = claudeManager.lastRepairResult {
                        HStack(spacing: 6) {
                            Image(systemName: result.success ? "checkmark.circle.fill" : "xmark.circle.fill")
                                .foregroundColor(result.success ? .green : .red)
                            Text(result.summary)
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }
                }

                Text("Uses Claude Code CLI to automatically diagnose and fix Swift errors")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Section("Claude API") {
                HStack {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("API Key")
                        if hasAPIKey {
                            Text("Configured")
                                .font(.caption)
                                .foregroundColor(.green)
                        }
                    }

                    Spacer()

                    if isEditingAPIKey {
                        SecureField("sk-ant-...", text: $apiKeyInput)
                            .textFieldStyle(.roundedBorder)
                            .frame(width: 180)

                        Button("Save") {
                            if !apiKeyInput.isEmpty {
                                settings.setCredential(platform: .gmail, key: "claude_api_key", value: apiKeyInput)
                            }
                            apiKeyInput = ""
                            isEditingAPIKey = false
                        }
                        .buttonStyle(.borderedProminent)
                        .controlSize(.small)

                        Button("Cancel") {
                            apiKeyInput = ""
                            isEditingAPIKey = false
                        }
                        .controlSize(.small)
                    } else {
                        Button(hasAPIKey ? "Change" : "Add Key") {
                            isEditingAPIKey = true
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                    }
                }

                Text("Get your API key from console.anthropic.com")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Section("Response Style") {
                Picker("Default tone", selection: Binding(
                    get: { Draft.Tone(rawValue: Defaults[.draftTone]) ?? .professional },
                    set: { Defaults[.draftTone] = $0.rawValue }
                )) {
                    ForEach(Draft.Tone.allCases, id: \.self) { tone in
                        Text(tone.displayName).tag(tone)
                    }
                }
            }

            Section("Model") {
                HStack {
                    Text("Model")
                    Spacer()
                    Text("Claude Sonnet 4")
                        .foregroundColor(.secondary)
                }
            }

            Section {
                HStack(spacing: 4) {
                    Image(systemName: "lock.shield.fill")
                        .font(.caption)
                    Text("API key stored locally in your Mac's Keychain")
                        .font(.caption)
                }
                .foregroundColor(.secondary)
            }
        }
        .formStyle(.grouped)
        .padding(Design.padding)
        .sheet(isPresented: $showingRepairSheet) {
            RepairSheet(error: testError)
        }
    }
}

// MARK: - Repair Sheet

private struct RepairSheet: View {
    let error: String
    @StateObject private var claudeManager = ClaudeManager.shared
    @Environment(\.dismiss) private var dismiss
    @State private var hasStarted = false

    var body: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                Text("Self-Healing Repair")
                    .font(.headline)
                Spacer()
                if claudeManager.isRepairing {
                    Button("Cancel") {
                        claudeManager.cancelRepair()
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                } else {
                    Button(action: { dismiss() }) {
                        Image(systemName: "xmark.circle.fill")
                            .font(.title2)
                            .foregroundColor(.secondary)
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding()

            Divider()

            // Status
            HStack(spacing: 8) {
                if claudeManager.isRepairing {
                    ProgressView()
                        .scaleEffect(0.8)
                    Text("Claude is analyzing and fixing the error...")
                        .font(.subheadline)
                } else if let result = claudeManager.lastRepairResult {
                    Image(systemName: result.success ? "checkmark.circle.fill" : "xmark.circle.fill")
                        .foregroundColor(result.success ? .green : .red)
                    Text(result.summary)
                        .font(.subheadline)
                } else {
                    Image(systemName: "sparkles")
                        .foregroundColor(.accentColor)
                    Text("Starting repair...")
                        .font(.subheadline)
                }
                Spacer()
            }
            .padding()
            .background(Color(nsColor: .controlBackgroundColor))

            // Output
            ScrollView {
                Text(claudeManager.repairOutput.isEmpty ? "Waiting for output..." : claudeManager.repairOutput)
                    .font(.system(.caption, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
            }

            Divider()

            // Footer
            HStack {
                if !claudeManager.isRepairing {
                    Button("Retry") {
                        startRepair()
                    }
                    .buttonStyle(.bordered)
                }

                Spacer()

                Button("Close") {
                    dismiss()
                }
                .keyboardShortcut(.cancelAction)
            }
            .padding()
        }
        .frame(width: 600, height: 450)
        .onAppear {
            if !hasStarted {
                hasStarted = true
                startRepair()
            }
        }
    }

    private func startRepair() {
        Task {
            // Get the Baku project path
            let projectPath = Bundle.main.bundlePath
                .replacingOccurrences(of: "/Products/Debug/Baku.app", with: "")
                .replacingOccurrences(of: "/.build/debug/Baku", with: "")

            _ = try? await claudeManager.repairBuildError(error, projectPath: projectPath)
        }
    }
}

// MARK: - Platform Config Sheet

struct PlatformConfigSheet: View {
    let platform: Platform
    let onDismiss: () -> Void

    @StateObject private var settings = SettingsManager.shared
    @StateObject private var discordManager = DiscordManager.shared
    @State private var selectedMethod: ConnectionMethod
    @State private var credentials: [String: String] = [:]
    @State private var showingRemoveAlert = false
    @State private var discordUser: DiscordUser?
    @State private var isTestingToken = false
    @State private var tokenError: String?

    init(platform: Platform, onDismiss: @escaping () -> Void) {
        self.platform = platform
        self.onDismiss = onDismiss
        _selectedMethod = State(initialValue: SettingsManager.shared.getConnectionMethod(for: platform))
    }

    var body: some View {
        VStack(spacing: 0) {
            // Header
            header

            Divider()

            // Content
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    connectionMethodPicker

                    if selectedMethod == .discordUserToken {
                        discordUserTokenSection
                    } else if selectedMethod.requiresCredentials {
                        credentialsForm
                    } else {
                        desktopIntegrationInfo
                    }
                }
                .padding(20)
            }

            Divider()

            // Footer
            footer
        }
        .frame(width: 440, height: platform == .discord && selectedMethod == .discordUserToken ? 600 : 400)
        .onAppear {
            loadCredentials()
            // Load Discord guilds if token exists
            if platform == .discord, let token = settings.getCredential(platform: .discord, key: "user_token") {
                credentials["user_token"] = token
                Task {
                    discordUser = try? await discordManager.testToken(token)
                    try? await discordManager.fetchGuilds()
                }
            } else if platform == .discord && selectedMethod == .discordUserToken {
                // Auto-show help for new users
                showingTokenHelp = true
            }
        }
        .onChange(of: selectedMethod) { _ in
            loadCredentials()
        }
        .alert("Remove Connection?", isPresented: $showingRemoveAlert) {
            Button("Cancel", role: .cancel) { }
            Button("Remove", role: .destructive) {
                removeConnection()
            }
        } message: {
            Text("This will remove all saved credentials for \(platform.displayName).")
        }
    }

    private var header: some View {
        HStack {
            Image(systemName: platform.iconName)
                .font(.title2)
                .foregroundColor(platform.accentColor)

            Text(platform.displayName)
                .font(.headline)

            Spacer()

            Button(action: onDismiss) {
                Image(systemName: "xmark.circle.fill")
                    .font(.title2)
                    .foregroundColor(.secondary)
            }
            .buttonStyle(.plain)
        }
        .padding(16)
    }

    private var connectionMethodPicker: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Connection Method")
                .font(.subheadline)
                .foregroundColor(.secondary)

            VStack(spacing: 8) {
                ForEach(platform.connectionMethods) { method in
                    ConnectionMethodOption(
                        method: method,
                        isSelected: selectedMethod == method,
                        onSelect: { selectedMethod = method }
                    )
                }
            }
        }
    }

    private var credentialsForm: some View {
        VStack(alignment: .leading, spacing: 12) {
            // Show Google Sign-In button for Gmail OAuth
            if selectedMethod == .gmailOAuth {
                googleSignInSection
            } else {
                // Regular credentials form
                Text("Credentials")
                    .font(.subheadline)
                    .foregroundColor(.secondary)

                ForEach(selectedMethod.credentialFields) { field in
                    VStack(alignment: .leading, spacing: 4) {
                        Text(field.label)
                            .font(.caption)
                            .foregroundColor(.secondary)

                        if field.isSecret {
                            SecureField(field.placeholder, text: binding(for: field.key))
                                .textFieldStyle(.roundedBorder)
                        } else {
                            TextField(field.placeholder, text: binding(for: field.key))
                                .textFieldStyle(.roundedBorder)
                        }
                    }
                }

                if let instructions = selectedMethod.setupInstructions {
                    Text(instructions)
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                if let url = selectedMethod.setupURL {
                    Link(destination: url) {
                        HStack(spacing: 4) {
                            Text("Get credentials")
                            Image(systemName: "arrow.up.right")
                        }
                        .font(.caption)
                    }
                }
            }
        }
    }

    @ViewBuilder
    private var googleSignInSection: some View {
        let googleAuth = GoogleAuthManager.shared

        VStack(alignment: .leading, spacing: 16) {
            if googleAuth.isSignedIn {
                // Already signed in
                HStack(spacing: 12) {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.title)
                        .foregroundColor(.green)

                    VStack(alignment: .leading, spacing: 4) {
                        Text("Signed in with Google")
                            .font(.headline)

                        if let email = googleAuth.userEmail {
                            Text(email)
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }

                    Spacer()

                    Button("Sign Out") {
                        googleAuth.signOut()
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                }
                .padding()
                .background(Color.green.opacity(0.1))
                .cornerRadius(Design.cornerRadius)
            } else {
                // Setup flow: credentials first, then sign-in
                VStack(alignment: .leading, spacing: 16) {
                    // Step 1: Get credentials
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Text("1. Create OAuth Credentials")
                                .font(.subheadline)
                                .fontWeight(.medium)

                            Spacer()

                            if let url = selectedMethod.setupURL {
                                Link(destination: url) {
                                    HStack(spacing: 4) {
                                        Text("Google Cloud Console")
                                        Image(systemName: "arrow.up.right")
                                    }
                                    .font(.caption)
                                }
                            }
                        }

                        ForEach(selectedMethod.credentialFields) { field in
                            VStack(alignment: .leading, spacing: 4) {
                                Text(field.label)
                                    .font(.caption)
                                    .foregroundColor(.secondary)

                                if field.isSecret {
                                    SecureField(field.placeholder, text: binding(for: field.key))
                                        .textFieldStyle(.roundedBorder)
                                } else {
                                    TextField(field.placeholder, text: binding(for: field.key))
                                        .textFieldStyle(.roundedBorder)
                                }
                            }
                        }
                    }

                    Divider()

                    // Step 2: Sign in
                    VStack(alignment: .leading, spacing: 8) {
                        Text("2. Sign in with Google")
                            .font(.subheadline)
                            .fontWeight(.medium)

                        Text("Opens your browser to sign in - no copy/paste needed!")
                            .font(.caption)
                            .foregroundColor(.secondary)

                        Button {
                            // Save credentials first
                            for field in selectedMethod.credentialFields {
                                if let value = credentials[field.key], !value.isEmpty {
                                    settings.setCredential(platform: platform, key: field.key, value: value)
                                }
                            }

                            Task {
                                do {
                                    try await googleAuth.signIn()
                                    save()
                                } catch {
                                    credentials["error"] = error.localizedDescription
                                }
                            }
                        } label: {
                            HStack(spacing: 8) {
                                if googleAuth.isAuthenticating {
                                    ProgressView()
                                        .scaleEffect(0.8)
                                } else {
                                    Image(systemName: "globe")
                                        .font(.title2)
                                }
                                Text(googleAuth.isAuthenticating ? "Waiting for sign-in..." : "Sign in with Google")
                                    .font(.headline)
                            }
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 12)
                        }
                        .buttonStyle(.borderedProminent)
                        .tint(Color(red: 0.26, green: 0.52, blue: 0.96))
                        .disabled(googleAuth.isAuthenticating || !hasRequiredCredentials)

                        if let errorMsg = credentials["error"] {
                            Text(errorMsg)
                                .font(.caption)
                                .foregroundColor(.red)
                        }
                    }
                }
            }
        }
    }

    private var hasRequiredCredentials: Bool {
        let clientId = credentials["client_id"] ?? ""
        let clientSecret = credentials["client_secret"] ?? ""
        return !clientId.isEmpty && !clientSecret.isEmpty
    }

    private var desktopIntegrationInfo: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 12) {
                Image(systemName: "checkmark.circle.fill")
                    .font(.title)
                    .foregroundColor(.green)

                VStack(alignment: .leading, spacing: 4) {
                    Text("No setup required")
                        .font(.headline)

                    if let instructions = selectedMethod.setupInstructions {
                        Text(instructions)
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                }
            }
            .padding()
            .background(Color.green.opacity(0.1))
            .cornerRadius(Design.cornerRadius)
        }
    }

    // MARK: - Discord User Token Section

    @State private var showingTokenHelp = false

    @ViewBuilder
    private var discordUserTokenSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Token input
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Text("User Token")
                        .font(.subheadline)
                        .foregroundColor(.secondary)

                    Spacer()

                    Button {
                        showingTokenHelp.toggle()
                    } label: {
                        HStack(spacing: 4) {
                            Image(systemName: "questionmark.circle")
                            Text("How to get token")
                        }
                        .font(.caption)
                    }
                    .buttonStyle(.plain)
                    .foregroundColor(.accentColor)
                }

                HStack {
                    SecureField("Paste your Discord token", text: binding(for: "user_token"))
                        .textFieldStyle(.roundedBorder)

                    Button {
                        testDiscordToken()
                    } label: {
                        if isTestingToken {
                            ProgressView()
                                .scaleEffect(0.7)
                        } else {
                            Text("Test")
                        }
                    }
                    .buttonStyle(.bordered)
                    .disabled(credentials["user_token"]?.isEmpty ?? true || isTestingToken)
                }

                if let error = tokenError {
                    Text(error)
                        .font(.caption)
                        .foregroundColor(.red)
                }

                if let user = discordUser {
                    HStack(spacing: 8) {
                        Image(systemName: "checkmark.circle.fill")
                            .foregroundColor(.green)
                        Text("Logged in as \(user.globalName ?? user.username)")
                            .font(.caption)
                            .foregroundColor(.green)
                    }
                }

                // Expandable help section
                if showingTokenHelp {
                    discordTokenHelpSection
                }
            }

            Divider()

            // Server/Guild selection
            if credentials["user_token"]?.isEmpty == false {
                // Token exists - show guild selector or loading state
                if !discordManager.guilds.isEmpty {
                    discordGuildSelector
                } else if discordManager.isLoading {
                    HStack {
                        ProgressView()
                            .scaleEffect(0.7)
                        Text("Loading servers...")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                    .frame(maxWidth: .infinity, alignment: .center)
                    .padding()
                } else {
                    VStack(spacing: 8) {
                        Text("No servers loaded")
                            .font(.caption)
                            .foregroundColor(.secondary)
                        Button("Load Servers") {
                            Task {
                                try? await discordManager.fetchGuilds()
                            }
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                    }
                    .frame(maxWidth: .infinity, alignment: .center)
                    .padding()
                }
            } else {
                Text("Enter your token and click Test to load your servers")
                    .font(.caption)
                    .foregroundColor(.secondary)
                    .frame(maxWidth: .infinity, alignment: .center)
                    .padding()
            }
        }
    }

    @StateObject private var claudeManager = ClaudeManager.shared
    @State private var isFetchingToken = false
    @State private var fetchError: String?

    @ViewBuilder
    private var discordTokenHelpSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Divider()

            // Auto-fetch option with Claude
            if claudeManager.canSelfHeal {
                VStack(alignment: .leading, spacing: 8) {
                    HStack {
                        Image(systemName: "sparkles")
                            .foregroundColor(.purple)
                        Text("Auto-fetch with Claude")
                            .font(.subheadline)
                            .fontWeight(.medium)
                    }

                    Text("Let Claude open Discord and grab your token automatically")
                        .font(.caption)
                        .foregroundColor(.secondary)

                    Button {
                        autoFetchToken()
                    } label: {
                        HStack(spacing: 8) {
                            if isFetchingToken {
                                ProgressView()
                                    .scaleEffect(0.7)
                                Text("Fetching token...")
                            } else {
                                Image(systemName: "wand.and.stars")
                                Text("Fetch Token Automatically")
                            }
                        }
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 8)
                    }
                    .buttonStyle(.borderedProminent)
                    .tint(.purple)
                    .disabled(isFetchingToken)

                    if let error = fetchError {
                        Text(error)
                            .font(.caption)
                            .foregroundColor(.red)
                    }
                }
                .padding(10)
                .background(Color.purple.opacity(0.1))
                .cornerRadius(8)

                Divider()
                    .padding(.vertical, 4)

                Text("Or do it manually:")
                    .font(.caption)
                    .foregroundColor(.secondary)
            } else {
                Text("Get your Discord token in 4 steps:")
                    .font(.subheadline)
                    .fontWeight(.medium)
            }

            VStack(alignment: .leading, spacing: 10) {
                HelpStep(number: 1, text: "Open Discord in your browser", action: "Open Discord") {
                    NSWorkspace.shared.open(URL(string: "https://discord.com/app")!)
                }

                HelpStep(number: 2, text: "Press ⌘⌥I to open DevTools, click Network tab")

                HelpStep(number: 3, text: "Type 'api' in the filter box, then click any request")

                HelpStep(number: 4, text: "In Headers, find 'Authorization' and copy the value")
            }

            HStack {
                Image(systemName: "lightbulb.fill")
                    .foregroundColor(.yellow)
                Text("The token is a long string starting with letters/numbers")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            .padding(.top, 4)
        }
        .padding(12)
        .background(Color(nsColor: .controlBackgroundColor).opacity(0.5))
        .cornerRadius(8)
    }

    private func autoFetchToken() {
        isFetchingToken = true
        fetchError = nil

        Task {
            do {
                let token = try await claudeManager.fetchDiscordToken()
                credentials["user_token"] = token
                // Automatically test the token
                testDiscordToken()
            } catch {
                fetchError = error.localizedDescription
            }
            isFetchingToken = false
        }
    }

    @State private var guildSearchText = ""

    private var filteredGuilds: [DiscordGuild] {
        let guilds = discordManager.guilds
        if guildSearchText.isEmpty {
            return Array(guilds.prefix(30)) // Show first 30 by default
        }
        return guilds.filter { $0.name.localizedCaseInsensitiveContains(guildSearchText) }
    }

    @ViewBuilder
    private var discordGuildSelector: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text("Select Servers (\(discordManager.guilds.count))")
                    .font(.subheadline)
                    .foregroundColor(.secondary)

                Spacer()

                if discordManager.isLoading {
                    ProgressView()
                        .scaleEffect(0.6)
                }

                Button("Refresh") {
                    Task {
                        try? await discordManager.fetchGuilds()
                    }
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
            }

            // Search field for many guilds
            if discordManager.guilds.count > 10 {
                TextField("Search servers...", text: $guildSearchText)
                    .textFieldStyle(.roundedBorder)
            }

            // Show selected servers first
            let selectedGuilds = discordManager.guilds.filter { settings.discordSelectedGuilds.contains($0.id) }
            if !selectedGuilds.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Selected")
                        .font(.caption2)
                        .foregroundColor(.secondary)
                        .textCase(.uppercase)

                    VStack(spacing: 4) {
                        ForEach(selectedGuilds) { guild in
                            DiscordGuildRow(
                                guild: guild,
                                isSelected: true
                            ) {
                                settings.toggleDiscordGuild(guild.id)
                            }
                        }
                    }
                }

                Divider()
                    .padding(.vertical, 4)
            }

            // Available servers (filtered)
            VStack(alignment: .leading, spacing: 4) {
                if !selectedGuilds.isEmpty || !guildSearchText.isEmpty {
                    Text(guildSearchText.isEmpty ? "Available" : "Search Results")
                        .font(.caption2)
                        .foregroundColor(.secondary)
                        .textCase(.uppercase)
                }

                let availableGuilds = filteredGuilds.filter { !settings.discordSelectedGuilds.contains($0.id) }
                if availableGuilds.isEmpty && !guildSearchText.isEmpty {
                    Text("No servers match '\(guildSearchText)'")
                        .font(.caption)
                        .foregroundColor(.secondary)
                        .padding(.vertical, 8)
                } else {
                    VStack(spacing: 4) {
                        ForEach(availableGuilds) { guild in
                            DiscordGuildRow(
                                guild: guild,
                                isSelected: false
                            ) {
                                settings.toggleDiscordGuild(guild.id)
                            }
                        }
                    }

                    if guildSearchText.isEmpty && discordManager.guilds.count > 30 {
                        Text("Showing 30 of \(discordManager.guilds.count) servers. Search to find more.")
                            .font(.caption)
                            .foregroundColor(.secondary)
                            .padding(.top, 4)
                    }
                }
            }

            Text("\(settings.discordSelectedGuilds.count) server\(settings.discordSelectedGuilds.count == 1 ? "" : "s") selected")
                .font(.caption)
                .foregroundColor(.accentColor)
                .padding(.top, 4)

            Divider()

            // DM toggle
            Toggle("Include Direct Messages", isOn: Binding(
                get: { settings.discordIncludeDMs },
                set: { settings.setDiscordIncludeDMs($0) }
            ))
            .font(.subheadline)
        }
    }

    private func testDiscordToken() {
        guard let token = credentials["user_token"], !token.isEmpty else { return }

        isTestingToken = true
        tokenError = nil

        Task {
            do {
                discordUser = try await discordManager.testToken(token)
                // Save the token
                settings.setCredential(platform: .discord, key: "user_token", value: token)
                // Load guilds
                try? await discordManager.fetchGuilds()
                try? await discordManager.fetchDMChannels()
            } catch {
                tokenError = error.localizedDescription
                discordUser = nil
            }
            isTestingToken = false
        }
    }

    private var footer: some View {
        HStack {
            if settings.isPlatformConfigured(platform) {
                Button("Remove") {
                    showingRemoveAlert = true
                }
                .foregroundColor(.red)
            }

            Spacer()

            Button("Cancel") {
                onDismiss()
            }
            .keyboardShortcut(.cancelAction)

            Button("Save") {
                save()
            }
            .keyboardShortcut(.defaultAction)
            .buttonStyle(.borderedProminent)
        }
        .padding(16)
    }

    // MARK: - Helpers

    private func binding(for key: String) -> Binding<String> {
        Binding(
            get: { credentials[key] ?? "" },
            set: { credentials[key] = $0 }
        )
    }

    private func loadCredentials() {
        credentials = [:]
        for field in selectedMethod.credentialFields {
            if let value = settings.getCredential(platform: platform, key: field.key) {
                credentials[field.key] = value
            }
        }
    }

    private func save() {
        // Save connection method
        settings.setConnectionMethod(selectedMethod, for: platform)

        // Save credentials
        for (key, value) in credentials where !value.isEmpty {
            settings.setCredential(platform: platform, key: key, value: value)
        }

        // Enable platform
        settings.setPlatformEnabled(platform, enabled: true)

        onDismiss()
    }

    private func removeConnection() {
        settings.clearAllCredentials(for: platform)
        settings.setPlatformEnabled(platform, enabled: false)
        onDismiss()
    }
}

// MARK: - Connection Method Option

private struct ConnectionMethodOption: View {
    let method: ConnectionMethod
    let isSelected: Bool
    let onSelect: () -> Void

    var body: some View {
        Button(action: onSelect) {
            HStack(spacing: 12) {
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .foregroundColor(isSelected ? .accentColor : .secondary)

                Image(systemName: method.iconName)
                    .frame(width: 20)
                    .foregroundColor(.secondary)

                VStack(alignment: .leading, spacing: 2) {
                    Text(method.displayName)
                        .font(.body)
                        .foregroundColor(.primary)

                    Text(method.subtitle)
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                Spacer()

                Text(method.complexity.rawValue)
                    .font(.caption2)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(method.complexity.color.opacity(0.2))
                    .foregroundColor(method.complexity.color)
                    .cornerRadius(4)
            }
            .padding(10)
            .background(isSelected ? Color.accentColor.opacity(0.1) : Color(nsColor: .controlBackgroundColor))
            .cornerRadius(Design.cornerRadius)
            .overlay(
                RoundedRectangle(cornerRadius: Design.cornerRadius)
                    .stroke(isSelected ? Color.accentColor : Color.clear, lineWidth: 1)
            )
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Platform Extensions (moved from old file)

extension Platform {
    var setupHelpText: String? {
        defaultConnectionMethod.setupInstructions
    }

    var setupURL: URL? {
        defaultConnectionMethod.setupURL
    }
}

// MARK: - Help Step

private struct HelpStep: View {
    let number: Int
    let text: String
    var action: String?
    var onAction: (() -> Void)?

    init(number: Int, text: String, action: String? = nil, onAction: (() -> Void)? = nil) {
        self.number = number
        self.text = text
        self.action = action
        self.onAction = onAction
    }

    var body: some View {
        HStack(alignment: .top, spacing: 10) {
            Text("\(number)")
                .font(.caption2)
                .fontWeight(.bold)
                .foregroundColor(.white)
                .frame(width: 18, height: 18)
                .background(Circle().fill(Color.accentColor))

            VStack(alignment: .leading, spacing: 4) {
                Text(text)
                    .font(.caption)

                if let action = action, let onAction = onAction {
                    Button(action) {
                        onAction()
                    }
                    .font(.caption)
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                }
            }
        }
    }
}

// MARK: - Discord Guild Row

private struct DiscordGuildRow: View {
    let guild: DiscordGuild
    let isSelected: Bool
    let onToggle: () -> Void

    var body: some View {
        Button(action: onToggle) {
            HStack(spacing: 10) {
                // Guild icon
                if let iconURL = guild.iconURL {
                    AsyncImage(url: iconURL) { image in
                        image
                            .resizable()
                            .aspectRatio(contentMode: .fill)
                    } placeholder: {
                        guildPlaceholder
                    }
                    .frame(width: 28, height: 28)
                    .clipShape(Circle())
                } else {
                    guildPlaceholder
                }

                // Guild name
                Text(guild.name)
                    .font(.body)
                    .lineLimit(1)

                Spacer()

                // Selection indicator
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .foregroundColor(isSelected ? .accentColor : .secondary)
            }
            .padding(.horizontal, 10)
            .padding(.vertical, 8)
            .background(isSelected ? Color.accentColor.opacity(0.1) : Color(nsColor: .controlBackgroundColor))
            .cornerRadius(Design.cornerRadius)
        }
        .buttonStyle(.plain)
    }

    private var guildPlaceholder: some View {
        ZStack {
            Circle()
                .fill(Color.gray.opacity(0.3))
                .frame(width: 28, height: 28)
            Text(String(guild.name.prefix(1)))
                .font(.caption)
                .fontWeight(.semibold)
                .foregroundColor(.secondary)
        }
    }
}

#Preview {
    SettingsView()
}
